---
- hosts: conteneurs
  remote_user: root

  tasks:
  - name: Installation des dépendances
    raw: apt update && apt install python-apt -y

  - name: Installation d'Apache2
    apt:
      name: apache2
      state: present
      update_cache: yes
      upgrade: full
...
