---
- hosts: pve1
  remote_user: root

# For non-Windows targets, use the copy module instead.
  tasks:
    - name: Install all security, critical, and rollup updates without a scheduled task
      win_updates:
        category_names:
          - SecurityUpdates
          - CriticalUpdates
          - UpdateRollups
        reboot: yes
...
