---
- hosts: 'proxmox'
  remote_user: 'root'
  vars:
    node: 'pve1'
    api_user: 'root@pam'
    api_password: 'digital'
    api_host: 'pve1.example.lan'
    storage: 'local-lvm'
    password: 'digital'
    debian: 'local:vztmpl/debian-10.0-standard_10.0-1_amd64.tar.gz'
    nextcloud: 'local:vztmpl/debian-9-turnkey-nextcloud_15.2-1_amd64.tar.gz'
    dokuwiki: 'local:vztmpl/debian-9-turnkey-dokuwiki_15.1-1_amd64.tar.gz'

  tasks:
  - name: Création du conteneur HAproxy
    proxmox:
      vmid: '200'
      node: '{{ node }}'
      storage: '{{ storage }}'
      api_user: '{{ api_user }}'
      api_password: '{{ api_password }}'
      api_host: '{{ api_host }}'
      password: '{{ password }}'
      searchdomain: 'tpdaniel.fr'
      hostname: 'haproxy'
      ostemplate: '{{ debian }}'
      nameserver: '8.8.8.8 8.8.4.4'
      netif: '{"net0":"name=eth0,ip=192.168.0.67/24,gw=192.168.0.1,bridge=vmbr1"}'
      cores: '1'
      cpus: '1'
      disk: '8'
      memory: '2048'
      swap: '1024'
      timeout: '90'
      state: 'present'

  - name: Création du conteneur Nextcloud
    proxmox:
      vmid: '201'
      node: '{{ node }}'
      storage: '{{ storage }}'
      api_user: '{{ api_user }}'
      api_password: '{{ api_password }}'
      api_host: '{{ api_host }}'
      password: '{{ password }}'
      searchdomain: 'next.tpdaniel.fr'
      hostname: 'nextcloud'
      ostemplate: '{{ nextcloud }}'
      nameserver: '8.8.8.8 8.8.4.4'
      netif: '{"net0":"name=eth0,ip=192.168.0.62/24,gw=192.168.0.1,bridge=vmbr1"}'
      cores: '1'
      cpus: '1'
      disk: '32'
      memory: '2048'
      swap: '1024'
      timeout: '90'
      state: 'present'

  - name: Création du conteneur Wiki
    proxmox:
      vmid: '202'
      node: '{{ node }}'
      storage: '{{ storage }}'
      api_user: '{{ api_user }}'
      api_password: '{{ api_password }}'
      api_host: '{{ api_host }}'
      password: '{{ password }}'
      searchdomain: 'web.tpdaniel.fr'
      hostname: 'web'
      ostemplate: '{{ dokuwiki }}'
      nameserver: '8.8.8.8 8.8.4.4'
      netif: '{"net0":"name=eth0,ip=192.168.0.61/24,gw=192.168.0.1,bridge=vmbr1"}'
      cores: '1'
      cpus: '1'
      disk: '16'
      memory: '2048'
      swap: '1024'
      timeout: '90'
      state: 'present' 

  - name: Lancement du conteneur Haproxy
    proxmox:
      vmid: '200'
      api_user: '{{ api_user }}'
      api_password: '{{ api_password }}'
      api_host: '{{ api_host }}'
      state: 'started'
      timeout: '90'

  - name: Lancement du conteneur Nextcloud
    proxmox:
      vmid: '201'
      api_user: '{{ api_user }}'
      api_password: '{{ api_password }}'
      api_host: '{{ api_host }}'
      state: 'started'
      timeout: '90'

  - name: Lancement du conteneur Wiki
    proxmox:
      vmid: '202'
      api_user: '{{ api_user }}'
      api_password: '{{ api_password }}'
      api_host: '{{ api_host }}'
      state: 'started'
      timeout: '90'
