---
- hosts: proxmox
  remote_user: root

  tasks:
  - name: création du conteneur Debian pour Nextcoud
    proxmox:
      vmid: '160'
      node: 'pve1'
      storage: 'local-zfs'
      api_user: 'root@pam'
      api_password: 'digital'
      api_host: 'pve1.example.lan'
      password: 'digital'
      searchdomain: 'nextcloud.lan'
      hostname: 'nextcloud'
      ostemplate: 'local:vztmpl/debian-10.0-standard_10.0-1_amd64.tar.gz'
      nameserver: '8.8.8.8 8.8.4.4'
      netif: '{"net0":"name=eth0,ip=192.168.0.220/24,gw=192.168.0.1,bridge=vmbr1"}'
      # netif: '{"net0":"name=eth0,ip=dhcp,ip6=dhcp,bridge=vmbr1"}'
      cores: '1'
      cpus: '1'
      disk: '12'
      memory: '2048'
      swap: '1024'
      timeout: '90'
      state: 'present'
...
