---
- hosts: pve1
  remote_user: root
  
  tasks:
  - name: Installation des dépendances sur un systeme de type Debian
    raw: apt update && apt install python-apt python3-apt -y
    when: ansible_os_family == 'Debian'

  - name: Installation des dépendances sur un systeme de type RedHat
    raw: dnf install python-dnf -y
    when: ansible_os_family == 'RedHat'
  
  - name: Mise à jour sur un systéme de type Debian
    apt:
      upgrade: full
      autoremove: yes
      autoclean: yes
      update_cache: yes
    when: ansible_os_family == 'Debian'
    
  - name: Mise à jour sur un systéme de type RedHat
    dnf:
      name: "*"
      state: latest
      autoremove: yes
      update_cache: yes
    when: ansible_os_family == 'RedHat'
...
